### ISSUE TITLE
Will you release the training and fine-tuning code?

### ISSUE THREAD

**Issue by WangHaoyuuu** [wsntxxn/BLAT#1]
I'm very interested in the technical details of your model. Is there any chance of getting access to the training and fine-tuning code?

**Comment by wsntxxn** [comment]
Hi Haoyu, this code base is actually old and I would suggest using model code from [LAION-CLAP](https://github.com/LAION-AI/CLAP) for training and fine-tuning if you do not want to make big modifications. A drawback of LAION-CLAP repo is that they use `webdataset` to pack audio and text data into tar files, which is not flexible enough.

The training of this repo can be found [here](https://github.com/wsntxxn/DCASE2022T6_CLAP). I have not updated it for long so hopefully it can still work. I will update it in README

**Comment by WangHaoyuuu** [comment]
Thank you！
